<?php

use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LeaveController;
// use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\ScheduleController as AdminScheduleController;
use App\Http\Controllers\Admin\LocationController as AdminLocationController;
use App\Http\Controllers\Admin\AttendanceController as AdminAttendanceController;
use App\Http\Controllers\Admin\LeaveController as AdminLeaveController;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

Route::get('/', function () {
    return redirect()->route('login');
});

// CSRF token route for debugging
Route::get('/csrf-token', function () {
    return response()->json(['csrf_token' => csrf_token()]);
});

// Health check route
Route::get('/health', function () {
    try {
        // Check database connection
        $databaseStatus = 'connected';
        try {
            DB::connection()->getPdo();
        } catch (Exception $e) {
            $databaseStatus = 'disconnected';
        }

        // Check storage writability
        $storageStatus = 'writable';
        try {
            $testFile = storage_path('logs/health-check-test.tmp');
            file_put_contents($testFile, 'test');
            if (!file_exists($testFile)) {
                $storageStatus = 'not_writable';
            } else {
                unlink($testFile);
            }
        } catch (Exception $e) {
            $storageStatus = 'not_writable';
        }

        $status = ($databaseStatus === 'connected' && $storageStatus === 'writable') ? 'ok' : 'error';

        return response()->json([
            'status' => $status,
            'database' => $databaseStatus,
            'storage' => $storageStatus,
            'timestamp' => now()->toISOString()
        ]);
    } catch (Exception $e) {
        return response()->json([
            'status' => 'error',
            'message' => 'Health check failed',
            'timestamp' => now()->toISOString()
        ], 500);
    }
});

// Refresh CSRF token route
Route::get('/refresh-csrf', function () {
    return response()->json(['csrf_token' => csrf_token()]);
});

// Test CSRF route
Route::post('/test-csrf', function (Illuminate\Http\Request $request) {
    return response()->json([
        'status' => 'success',
        'message' => 'CSRF token is valid',
        'csrf_token' => csrf_token(),
        'session_id' => session()->getId()
    ]);
});

// Auth routes (will be generated by Breeze)
require __DIR__ . '/auth.php';

Route::middleware(['auth', 'verified'])->group(function () {
    // Dashboard
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Presensi
    Route::get('/attendance', [AttendanceController::class, 'index'])->name('attendance.index');
    Route::post('/attendance/check-in', [AttendanceController::class, 'checkIn'])->name('attendance.checkin');
    Route::post('/attendance/check-out', [AttendanceController::class, 'checkOut'])->name('attendance.checkout');
    Route::get('/attendance/history', [AttendanceController::class, 'history'])->name('attendance.history');

    // Leave/Izin
    Route::get('/attendance/leaves', [LeaveController::class, 'index'])->name('leaves.index');
    Route::post('/attendance/leave', [LeaveController::class, 'store'])->name('leave.store');

    // Jadwal
    Route::get('/schedules', [ScheduleController::class, 'index'])->name('schedules.index');

    // Profile
    // Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    // Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    // Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// Admin Routes
Route::middleware(['auth', 'verified', 'admin'])->prefix('admin')->name('admin.')->group(function () {
    // Admin Dashboard
    Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');

    // User Management
    Route::resource('users', AdminUserController::class);

    // Schedule Management
    Route::resource('schedules', AdminScheduleController::class);

    // Location Management
    Route::resource('locations', AdminLocationController::class);

    // Attendance Management
    Route::resource('attendances', AdminAttendanceController::class);
    Route::post('attendances/{attendance}/approve', [AdminAttendanceController::class, 'approve'])->name('attendances.approve');
    Route::post('attendances/{attendance}/reject', [AdminAttendanceController::class, 'reject'])->name('attendances.reject');

    // Leave Management
    Route::get('leaves', [AdminLeaveController::class, 'index'])->name('leaves.index');
    Route::post('leaves/{leave}/approve', [AdminLeaveController::class, 'approve'])->name('leaves.approve');
    Route::post('leaves/{leave}/reject', [AdminLeaveController::class, 'reject'])->name('leaves.reject');
    Route::delete('leaves/{leave}', [AdminLeaveController::class, 'destroy'])->name('leaves.destroy');
});
